package com.myspace.rest_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String hi;

	private java.lang.Boolean whatsUp;

	private java.lang.Long KP;

	private int luka;

	private java.math.BigDecimal JJ;

	private java.lang.Short test;

	private java.math.BigDecimal test1;

	public test() {
	}

	public java.lang.String getHi() {
		return this.hi;
	}

	public void setHi(java.lang.String hi) {
		this.hi = hi;
	}

	public java.lang.Boolean getWhatsUp() {
		return this.whatsUp;
	}

	public void setWhatsUp(java.lang.Boolean whatsUp) {
		this.whatsUp = whatsUp;
	}

	public java.lang.Long getKP() {
		return this.KP;
	}

	public void setKP(java.lang.Long KP) {
		this.KP = KP;
	}

	public int getLuka() {
		return this.luka;
	}

	public void setLuka(int luka) {
		this.luka = luka;
	}

	public java.math.BigDecimal getJJ() {
		return this.JJ;
	}

	public void setJJ(java.math.BigDecimal JJ) {
		this.JJ = JJ;
	}

	public java.lang.Short getTest() {
		return this.test;
	}

	public void setTest(java.lang.Short test) {
		this.test = test;
	}

	public java.math.BigDecimal getTest1() {
		return this.test1;
	}

	public void setTest1(java.math.BigDecimal test1) {
		this.test1 = test1;
	}

	public test(java.lang.String hi, java.lang.Boolean whatsUp,
			java.lang.Long KP, int luka, java.math.BigDecimal JJ,
			java.lang.Short test, java.math.BigDecimal test1) {
		this.hi = hi;
		this.whatsUp = whatsUp;
		this.KP = KP;
		this.luka = luka;
		this.JJ = JJ;
		this.test = test;
		this.test1 = test1;
	}

}