package com.myspace.rest_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String hi;

	public test() {
	}

	public java.lang.String getHi() {
		return this.hi;
	}

	public void setHi(java.lang.String hi) {
		this.hi = hi;
	}

	public test(java.lang.String hi) {
		this.hi = hi;
	}

}